- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional
        # NOTE(iurygregory) Only run this two jobs since we are testing
        # wholedisk + partition on tempest
        # NOTE(TheJulia): Disabling as the centos base image url is no longer
        # available and returns a 404.
        # - ipa-tempest-bios-ipmi-direct-src
        # - ipa-tempest-uefi-redfish-vmedia-src
        # NOTE(TheJulia): Metalsmith is using focal nodes :\
        #- metalsmith-integration-ipa-src-uefi
        #- metalsmith-integration-ipa-src-legacy
        - ironic-standalone-ipa-src
        # NOTE(dtantsur): non-voting because IPA source code is very unlikely
        # to break them. They rather serve as a canary for broken POST jobs.
        - ironic-python-agent-check-image-tinyipa:
            voting: false
        - ironic-python-agent-check-image-dib-centos9:
            voting: false
            nodeset: ubuntu-jammy
        # Non-voting jobs
        - ipa-tox-bandit:
            voting: false
    gate:
      jobs:
        - openstack-tox-functional
        # NOTE(TheJulia): Disabling as the centos base image url is no longer
        # available and returns a 404.
        # - ipa-tempest-bios-ipmi-direct-src
        # - ipa-tempest-uefi-redfish-vmedia-src
        # NOTE(TheJulia): Metalsmith is using focal nodes :\
        #- metalsmith-integration-ipa-src-uefi
        #- metalsmith-integration-ipa-src-legacy
        - ironic-standalone-ipa-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
        - ironic-python-agent-build-image-dib-centos9
